datamodule:
  image_dir: /home/irteam/junghye-dcloud-dir/Pixt/code/Pixt/data/
  annotation_dir:
    train: /home/irteam/junghye-dcloud-dir/Pixt/code/Pixt/data/annotation/annotation_merged_remove_gap/train.csv
    valid: /home/irteam/junghye-dcloud-dir/Pixt/code/Pixt/data/annotation/annotation_merged_remove_gap/valid.csv
  num_workers: 24
  batch_size: 16
  test_batch_size: 1

loss:
  ce_loss_weight: 1.0

module:
  classes_ko_dir: /home/irteam/junghye-dcloud-dir/Pixt/code/Pixt/data/annotation/all_class_list_ko.pt
  classes_en_dir: /home/irteam/junghye-dcloud-dir/Pixt/code/Pixt/data/annotation/all_class_list_en.pt
  max_length: 300
  lr: 5.0e-05

logger:
  save_root: '/home/irteam/junghye-dcloud-dir/Pixt/code/Pixt/outputs'
  log_dirname: 'pixt_baseline'
  name: lightning_logs

callbacks:
  checkpoint:
    monitor: valid\ce_loss
    save_top_k: 1
    mode: min

trainer:
  accelerator: gpu
  devices: 0
  max_epochs: 30