datamodule:
  image_dir: c:\pixt\data\
  annotation_dir:
    train: c:\pixt\data\annotation\annotation_merged_remove_gap\train.csv
    valid: c:\pixt\data\annotation\annotation_merged_remove_gap\valid.csv
  num_workers: 0
  batch_size: 16
  test_batch_size: 1

loss:
  base_loss_weight: 1.0

module:
  encoder:
    image:
      input_resolution: 224
      layers: [3,4,6,3]
      width: 64
      heads: 32
      output_dim: 1024
    text:
      width: 512
      layers: 12
      heads: 8

  classes_ko_dir: c:\pixt\data\annotation\all_class_list_ko.pt
  classes_en_dir: c:\pixt\data\annotation\all_class_list_en.pt
  max_length: 500
  lr: 1.0e-03

logger:
  save_root: 'c:\pixt\outputs'
  log_dirname: 'pixt_baseline'
  name: lightning_logs

callbacks:
  checkpoint:
    monitor: valid/mlsm_loss
    save_top_k: 1
    mode: min

trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 30