datamodule:
  image_dir: /home/irteam/junghye-dcloud-dir/Pixt/code/Pixt/data/
  annotation_dir:
    train: /home/irteam/junghye-dcloud-dir/Pixt/code/Pixt/data/annotation/annotation_remove_mgf/train_reduction.csv
    valid: /home/irteam/junghye-dcloud-dir/Pixt/code/Pixt/data/annotation/annotation_remove_mgf/valid.csv
  num_workers: 24
  batch_size: 8
  test_batch_size: 1

loss:
  ce_loss_weight: 1.0

module:
  classes_ko_dir: /home/irteam/junghye-dcloud-dir/Pixt/code/Pixt/data/annotation/all_class_list_ko.pt
  classes_en_dir: /home/irteam/junghye-dcloud-dir/Pixt/code/Pixt/data/annotation/all_class_list_en.pt
  max_length: 70
  lr: 1.0e-05

 
logger:
  save_root: '/home/irteam/junghye-dcloud-dir/Pixt/code/Pixt/outputs'
  log_dirname: 'pixt_baseline'
  name: lightning_logs

callbacks:
  checkpoint:
    monitor: valid/mlsm_loss
    save_top_k: 1
    mode: min

trainer:
  accelerator: gpu
  devices: 0
  max_epochs: 250
  accumulate_grad_batches: 1 